
//**********************************************************************`
//* This is an include file generated by EtwPlusTool.                  *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
#pragma pack(push, 16)

#include "EtwPlus.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Field Descriptors, used in the ETX_EVENT_DESCRIPTOR array below
//
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_AchievementGet_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_AchievemntUnlocked_Fields[13] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_BanLevel_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_BlockBroken_Fields[7] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_UInt64,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_BlockPlaced_Fields[7] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_UInt64,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_ChestfulOfCobblestone_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_EnteredNewBiome_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_GameProgress_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Float,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_IncDistanceTravelled_Fields[6] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_UInt64,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_IncTimePlayed_Fields[5] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_UInt64,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_LeaderboardTotals_Fields[6] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_LevelExit_Fields[12] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_LevelResume_Fields[17] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_LevelSaveOrCheckpoint_Fields[13] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_LevelStart_Fields[16] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_McItemAcquired_Fields[14] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Int32,0},{EtxFieldType_UInt64,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_McItemUsed_Fields[14] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Int32,0},{EtxFieldType_UInt64,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_MenuShown_Fields[13] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_MobInteract_Fields[5] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_MobKilled_Fields[18] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_MultiplayerRoundEnd_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_MultiplayerRoundStart_Fields[9] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_OnARail_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_Overkill_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_PauseOrInactive_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_PlayedMusicDisc_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_PlayerDiedOrFailed_Fields[18] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_PlayerSessionEnd_Fields[7] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_PlayerSessionPause_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_PlayerSessionResume_Fields[6] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_PlayerSessionStart_Fields[6] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_RecordMediaShareUpload_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_RichPresenceState_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_SkinChanged_Fields[12] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_TexturePackLoaded_Fields[13] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Boolean,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_UnbanLevel_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_UnpauseOrActive_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_UpsellPresented_Fields[13] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR XBLA_149E11AE_UpsellResponded_Fields[14] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};

// Event name mapping
//
#define AchievementGet_value 1
#define AchievemntUnlocked_value 2
#define BanLevel_value 3
#define BlockBroken_value 4
#define BlockPlaced_value 5
#define ChestfulOfCobblestone_value 6
#define EnteredNewBiome_value 7
#define GameProgress_value 8
#define IncDistanceTravelled_value 9
#define IncTimePlayed_value 10
#define LeaderboardTotals_value 11
#define LevelExit_value 12
#define LevelResume_value 13
#define LevelSaveOrCheckpoint_value 14
#define LevelStart_value 15
#define McItemAcquired_value 16
#define McItemUsed_value 17
#define MenuShown_value 18
#define MobInteract_value 19
#define MobKilled_value 20
#define MultiplayerRoundEnd_value 21
#define MultiplayerRoundStart_value 22
#define OnARail_value 23
#define Overkill_value 24
#define PauseOrInactive_value 25
#define PlayedMusicDisc_value 26
#define PlayerDiedOrFailed_value 27
#define PlayerSessionEnd_value 28
#define PlayerSessionPause_value 29
#define PlayerSessionResume_value 30
#define PlayerSessionStart_value 31
#define RecordMediaShareUpload_value 32
#define RichPresenceState_value 33
#define SkinChanged_value 34
#define TexturePackLoaded_value 35
#define UnbanLevel_value 36
#define UnpauseOrActive_value 37
#define UpsellPresented_value 38
#define UpsellResponded_value 39

// Event Descriptor array
//
EXTERN_C __declspec(selectany) ETX_EVENT_DESCRIPTOR XBLA_149E11AEEvents[39] =  {
    {{ 1, 1, 0, 0, 0, 0, 0x0 }, "AchievementGet", "0.7.IGB-2.1", XBLA_149E11AE_AchievementGet_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 2, 1, 0, 0, 0, 0, 0x0 }, "AchievemntUnlocked", "0.7.IGB-2.1", XBLA_149E11AE_AchievemntUnlocked_Fields, 13, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 3, 1, 0, 0, 0, 0, 0x0 }, "BanLevel", "0.7.IGB-2.1", XBLA_149E11AE_BanLevel_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 4, 1, 0, 0, 0, 0, 0x0 }, "BlockBroken", "0.7.IGB-2.1", XBLA_149E11AE_BlockBroken_Fields, 7, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 5, 1, 0, 0, 0, 0, 0x0 }, "BlockPlaced", "0.7.IGB-2.1", XBLA_149E11AE_BlockPlaced_Fields, 7, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 6, 1, 0, 0, 0, 0, 0x0 }, "ChestfulOfCobblestone", "0.7.IGB-2.1", XBLA_149E11AE_ChestfulOfCobblestone_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 7, 2, 0, 0, 0, 0, 0x0 }, "EnteredNewBiome", "0.7.IGB-2.2", XBLA_149E11AE_EnteredNewBiome_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 8, 0, 0, 0, 0, 0, 0x0 }, "GameProgress", "0.7.IGGP-2.0", XBLA_149E11AE_GameProgress_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 9, 2, 0, 0, 0, 0, 0x0 }, "IncDistanceTravelled", "0.7.IGB-2.2", XBLA_149E11AE_IncDistanceTravelled_Fields, 6, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 10, 1, 0, 0, 0, 0, 0x0 }, "IncTimePlayed", "0.7.IGB-2.1", XBLA_149E11AE_IncTimePlayed_Fields, 5, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 11, 1, 0, 0, 0, 0, 0x0 }, "LeaderboardTotals", "0.7.IGB-2.1", XBLA_149E11AE_LeaderboardTotals_Fields, 6, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 12, 1, 0, 0, 0, 0, 0x0 }, "LevelExit", "0.7.IGB-2.1", XBLA_149E11AE_LevelExit_Fields, 12, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 13, 1, 0, 0, 0, 0, 0x0 }, "LevelResume", "0.7.IGB-2.1", XBLA_149E11AE_LevelResume_Fields, 17, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 14, 1, 0, 0, 0, 0, 0x0 }, "LevelSaveOrCheckpoint", "0.7.IGB-2.1", XBLA_149E11AE_LevelSaveOrCheckpoint_Fields, 13, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 15, 1, 0, 0, 0, 0, 0x0 }, "LevelStart", "0.7.IGB-2.1", XBLA_149E11AE_LevelStart_Fields, 16, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 16, 1, 0, 0, 0, 0, 0x0 }, "McItemAcquired", "0.7.IGIA-2.1", XBLA_149E11AE_McItemAcquired_Fields, 14, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 17, 2, 0, 0, 0, 0, 0x0 }, "McItemUsed", "0.7.IGIU-2.2", XBLA_149E11AE_McItemUsed_Fields, 14, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 18, 1, 0, 0, 0, 0, 0x0 }, "MenuShown", "0.7.IGB-2.1", XBLA_149E11AE_MenuShown_Fields, 13, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 19, 2, 0, 0, 0, 0, 0x0 }, "MobInteract", "0.7.IGB-2.2", XBLA_149E11AE_MobInteract_Fields, 5, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 20, 3, 0, 0, 0, 0, 0x0 }, "MobKilled", "0.7.IGED-2.3", XBLA_149E11AE_MobKilled_Fields, 18, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 21, 0, 0, 0, 0, 0, 0x0 }, "MultiplayerRoundEnd", "0.7.IGMRE-2.0", XBLA_149E11AE_MultiplayerRoundEnd_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 22, 0, 0, 0, 0, 0, 0x0 }, "MultiplayerRoundStart", "0.7.IGMRS-2.0", XBLA_149E11AE_MultiplayerRoundStart_Fields, 9, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 23, 1, 0, 0, 0, 0, 0x0 }, "OnARail", "0.7.IGB-2.1", XBLA_149E11AE_OnARail_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 24, 1, 0, 0, 0, 0, 0x0 }, "Overkill", "0.7.IGB-2.1", XBLA_149E11AE_Overkill_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 25, 1, 0, 0, 0, 0, 0x0 }, "PauseOrInactive", "0.7.IGB-2.1", XBLA_149E11AE_PauseOrInactive_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 26, 1, 0, 0, 0, 0, 0x0 }, "PlayedMusicDisc", "0.7.IGB-2.1", XBLA_149E11AE_PlayedMusicDisc_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 27, 1, 0, 0, 0, 0, 0x0 }, "PlayerDiedOrFailed", "0.7.IGB-2.1", XBLA_149E11AE_PlayerDiedOrFailed_Fields, 18, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 28, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionEnd", "0.7.IGPSE-2.0", XBLA_149E11AE_PlayerSessionEnd_Fields, 7, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 29, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionPause", "0.7.IGPSPA-2.0", XBLA_149E11AE_PlayerSessionPause_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 30, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionResume", "0.7.IGPSR-2.0", XBLA_149E11AE_PlayerSessionResume_Fields, 6, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 31, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionStart", "0.7.IGPSS-2.0", XBLA_149E11AE_PlayerSessionStart_Fields, 6, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 32, 1, 0, 0, 0, 0, 0x0 }, "RecordMediaShareUpload", "0.7.IGB-2.1", XBLA_149E11AE_RecordMediaShareUpload_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 33, 1, 0, 0, 0, 0, 0x0 }, "RichPresenceState", "0.7.IGB-2.1", XBLA_149E11AE_RichPresenceState_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 34, 1, 0, 0, 0, 0, 0x0 }, "SkinChanged", "0.7.IGB-2.1", XBLA_149E11AE_SkinChanged_Fields, 12, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 35, 1, 0, 0, 0, 0, 0x0 }, "TexturePackLoaded", "0.7.IGB-2.1", XBLA_149E11AE_TexturePackLoaded_Fields, 13, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 36, 1, 0, 0, 0, 0, 0x0 }, "UnbanLevel", "0.7.IGB-2.1", XBLA_149E11AE_UnbanLevel_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 37, 1, 0, 0, 0, 0, 0x0 }, "UnpauseOrActive", "0.7.IGB-2.1", XBLA_149E11AE_UnpauseOrActive_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 38, 1, 0, 0, 0, 0, 0x0 }, "UpsellPresented", "0.7.IGB-2.1", XBLA_149E11AE_UpsellPresented_Fields, 13, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 39, 1, 0, 0, 0, 0, 0x0 }, "UpsellResponded", "0.7.IGB-2.1", XBLA_149E11AE_UpsellResponded_Fields, 14, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault }};

// Provider Descriptor for XBLA_149E11AE
//
EXTERN_C __declspec(selectany) ETX_PROVIDER_DESCRIPTOR XBLA_149E11AEProvider = {"XBLA_149E11AE", {0xee9ef54b,0xfe67,0x4a89,{0x80,0xa8,0x52,0xcc,0xa1,0x6b,0xe7,0x84}}, 39, (ETX_EVENT_DESCRIPTOR*)&XBLA_149E11AEEvents, 0, EtxProviderEnabledState_Undefined, EtxProviderEnabledState_OnByDefault, 0, 100, EtxProviderLatency_Undefined, EtxProviderLatency_RealTime, EtxProviderPriority_Undefined, EtxProviderPriority_Critical};

// ETW handle for XBLA_149E11AE
//
EXTERN_C __declspec(selectany) REGHANDLE XBLA_149E11AEHandle = (REGHANDLE)0;

/*++

Routine Description:

    Register the provider with ETW+.

Arguments:
    
    None

Remarks:

    ERROR_SUCCESS if success or if the provider was already registered. 
    Otherwise, an error code.

--*/
#define EventRegisterXBLA_149E11AE() EtxRegister(&XBLA_149E11AEProvider, &XBLA_149E11AEHandle)

/*++

Routine Description:

    Unregister the provider from ETW+.

Arguments:
            None
Remarks:
    ERROR_SUCCESS if success or if the provider was not registered. 
    Otherwise, an error code.
--*/
#define EventUnregisterXBLA_149E11AE() EtxUnregister(&XBLA_149E11AEProvider, &XBLA_149E11AEHandle)

#define EventEnabledAchievementGet() (TRUE)

// Entry point to log the event AchievementGet
//
__inline
ULONG
EventWriteAchievementGet(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int AchievementId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_AchievementGet 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_AchievementGet];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &AchievementId, sizeof(AchievementId));

    return EtxEventWrite(&XBLA_149E11AEEvents[0], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_AchievementGet, EventData);
}
#define EventEnabledAchievemntUnlocked() (TRUE)

// Entry point to log the event AchievemntUnlocked
//
__inline
ULONG
EventWriteAchievemntUnlocked(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int AchievementId, __in const signed int AchievementGamerscore)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_AchievemntUnlocked 13

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_AchievemntUnlocked];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &AchievementId, sizeof(AchievementId));
    EventDataDescCreate(&EventData[12], &AchievementGamerscore, sizeof(AchievementGamerscore));

    return EtxEventWrite(&XBLA_149E11AEEvents[1], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_AchievemntUnlocked, EventData);
}
#define EventEnabledBanLevel() (TRUE)

// Entry point to log the event BanLevel
//
__inline
ULONG
EventWriteBanLevel(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_BanLevel 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_BanLevel];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));

    return EtxEventWrite(&XBLA_149E11AEEvents[2], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_BanLevel, EventData);
}
#define EventEnabledBlockBroken() (TRUE)

// Entry point to log the event BlockBroken
//
__inline
ULONG
EventWriteBlockBroken(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int DifficultyLevelId, __in const signed int BlockId, __in const signed int BlockAux, __in const unsigned __int64 BlockCount)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_BlockBroken 7

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_BlockBroken];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[4], &BlockId, sizeof(BlockId));
    EventDataDescCreate(&EventData[5], &BlockAux, sizeof(BlockAux));
    EventDataDescCreate(&EventData[6], &BlockCount, sizeof(BlockCount));

    return EtxEventWrite(&XBLA_149E11AEEvents[3], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_BlockBroken, EventData);
}
#define EventEnabledBlockPlaced() (TRUE)

// Entry point to log the event BlockPlaced
//
__inline
ULONG
EventWriteBlockPlaced(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int DifficultyLevelId, __in const signed int BlockId, __in const signed int BlockAux, __in const unsigned __int64 BlockCount)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_BlockPlaced 7

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_BlockPlaced];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[4], &BlockId, sizeof(BlockId));
    EventDataDescCreate(&EventData[5], &BlockAux, sizeof(BlockAux));
    EventDataDescCreate(&EventData[6], &BlockCount, sizeof(BlockCount));

    return EtxEventWrite(&XBLA_149E11AEEvents[4], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_BlockPlaced, EventData);
}
#define EventEnabledChestfulOfCobblestone() (TRUE)

// Entry point to log the event ChestfulOfCobblestone
//
__inline
ULONG
EventWriteChestfulOfCobblestone(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int Cobblecount)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_ChestfulOfCobblestone 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_ChestfulOfCobblestone];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &Cobblecount, sizeof(Cobblecount));

    return EtxEventWrite(&XBLA_149E11AEEvents[5], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_ChestfulOfCobblestone, EventData);
}
#define EventEnabledEnteredNewBiome() (TRUE)

// Entry point to log the event EnteredNewBiome
//
__inline
ULONG
EventWriteEnteredNewBiome(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int BiomeId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_EnteredNewBiome 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_EnteredNewBiome];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &BiomeId, sizeof(BiomeId));

    return EtxEventWrite(&XBLA_149E11AEEvents[6], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_EnteredNewBiome, EventData);
}
#define EventEnabledGameProgress() (TRUE)

// Entry point to log the event GameProgress
//
__inline
ULONG
EventWriteGameProgress(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const float CompletionPercent)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_GameProgress 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_GameProgress];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &CompletionPercent, sizeof(CompletionPercent));

    return EtxEventWrite(&XBLA_149E11AEEvents[7], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_GameProgress, EventData);
}
#define EventEnabledIncDistanceTravelled() (TRUE)

// Entry point to log the event IncDistanceTravelled
//
__inline
ULONG
EventWriteIncDistanceTravelled(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int DifficultyLevelId, __in const unsigned __int64 Distance, __in const signed int TravelMethodId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_IncDistanceTravelled 6

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_IncDistanceTravelled];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[4], &Distance, sizeof(Distance));
    EventDataDescCreate(&EventData[5], &TravelMethodId, sizeof(TravelMethodId));

    return EtxEventWrite(&XBLA_149E11AEEvents[8], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_IncDistanceTravelled, EventData);
}
#define EventEnabledIncTimePlayed() (TRUE)

// Entry point to log the event IncTimePlayed
//
__inline
ULONG
EventWriteIncTimePlayed(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int DifficultyLevelId, __in const unsigned __int64 TimePlayed)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_IncTimePlayed 5

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_IncTimePlayed];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[4], &TimePlayed, sizeof(TimePlayed));

    return EtxEventWrite(&XBLA_149E11AEEvents[9], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_IncTimePlayed, EventData);
}
#define EventEnabledLeaderboardTotals() (TRUE)

// Entry point to log the event LeaderboardTotals
//
__inline
ULONG
EventWriteLeaderboardTotals(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int DifficultyLevelId, __in const signed int LeaderboardId, __in const signed int Count)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_LeaderboardTotals 6

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_LeaderboardTotals];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[4], &LeaderboardId, sizeof(LeaderboardId));
    EventDataDescCreate(&EventData[5], &Count, sizeof(Count));

    return EtxEventWrite(&XBLA_149E11AEEvents[10], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_LeaderboardTotals, EventData);
}
#define EventEnabledLevelExit() (TRUE)

// Entry point to log the event LevelExit
//
__inline
ULONG
EventWriteLevelExit(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID MultiplayerCorrelationId, __in const signed int LevelExitStatus, __in LPCGUID PlayerSession)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_LevelExit 12

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_LevelExit];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[10], &LevelExitStatus, sizeof(LevelExitStatus));
    EventDataDescCreate(&EventData[11], PlayerSession, sizeof(GUID));

    return EtxEventWrite(&XBLA_149E11AEEvents[11], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_LevelExit, EventData);
}
#define EventEnabledLevelResume() (TRUE)

// Entry point to log the event LevelResume
//
__inline
ULONG
EventWriteLevelResume(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int FriendsOrMatch, __in const signed int CompeteOrCoop, __in const signed int DifficultyId, __in const signed int NumberOfLocalPlayers, __in const signed int NumberOfOnlinePlayers, __in const signed int SaveOrCheckpointId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_LevelResume 17

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_LevelResume];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &FriendsOrMatch, sizeof(FriendsOrMatch));
    EventDataDescCreate(&EventData[12], &CompeteOrCoop, sizeof(CompeteOrCoop));
    EventDataDescCreate(&EventData[13], &DifficultyId, sizeof(DifficultyId));
    EventDataDescCreate(&EventData[14], &NumberOfLocalPlayers, sizeof(NumberOfLocalPlayers));
    EventDataDescCreate(&EventData[15], &NumberOfOnlinePlayers, sizeof(NumberOfOnlinePlayers));
    EventDataDescCreate(&EventData[16], &SaveOrCheckpointId, sizeof(SaveOrCheckpointId));

    return EtxEventWrite(&XBLA_149E11AEEvents[12], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_LevelResume, EventData);
}
#define EventEnabledLevelSaveOrCheckpoint() (TRUE)

// Entry point to log the event LevelSaveOrCheckpoint
//
__inline
ULONG
EventWriteLevelSaveOrCheckpoint(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int SaveOrCheckpointId, __in const signed int SaveSizeInBytes)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_LevelSaveOrCheckpoint 13

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_LevelSaveOrCheckpoint];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &SaveOrCheckpointId, sizeof(SaveOrCheckpointId));
    EventDataDescCreate(&EventData[12], &SaveSizeInBytes, sizeof(SaveSizeInBytes));

    return EtxEventWrite(&XBLA_149E11AEEvents[13], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_LevelSaveOrCheckpoint, EventData);
}
#define EventEnabledLevelStart() (TRUE)

// Entry point to log the event LevelStart
//
__inline
ULONG
EventWriteLevelStart(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID MultiplayerCorrelationId, __in const signed int FriendsOrMatch, __in const signed int CompeteOrCoop, __in const signed int DifficultyId, __in const signed int NumberOfLocalPlayers, __in const signed int NumberOfOnlinePlayers, __in LPCGUID PlayerSession)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_LevelStart 16

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_LevelStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[10], &FriendsOrMatch, sizeof(FriendsOrMatch));
    EventDataDescCreate(&EventData[11], &CompeteOrCoop, sizeof(CompeteOrCoop));
    EventDataDescCreate(&EventData[12], &DifficultyId, sizeof(DifficultyId));
    EventDataDescCreate(&EventData[13], &NumberOfLocalPlayers, sizeof(NumberOfLocalPlayers));
    EventDataDescCreate(&EventData[14], &NumberOfOnlinePlayers, sizeof(NumberOfOnlinePlayers));
    EventDataDescCreate(&EventData[15], PlayerSession, sizeof(GUID));

    return EtxEventWrite(&XBLA_149E11AEEvents[14], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_LevelStart, EventData);
}
#define EventEnabledMcItemAcquired() (TRUE)

// Entry point to log the event McItemAcquired
//
__inline
ULONG
EventWriteMcItemAcquired(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ItemId, __in const signed int AcquisitionMethodId, __in const float LocationX, __in const float LocationY, __in const float LocationZ, __in const signed int ItemAux, __in const unsigned __int64 ItemCount)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_McItemAcquired 14

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_McItemAcquired];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], &ItemId, sizeof(ItemId));
    EventDataDescCreate(&EventData[8], &AcquisitionMethodId, sizeof(AcquisitionMethodId));
    EventDataDescCreate(&EventData[9], &LocationX, sizeof(LocationX));
    EventDataDescCreate(&EventData[10], &LocationY, sizeof(LocationY));
    EventDataDescCreate(&EventData[11], &LocationZ, sizeof(LocationZ));
    EventDataDescCreate(&EventData[12], &ItemAux, sizeof(ItemAux));
    EventDataDescCreate(&EventData[13], &ItemCount, sizeof(ItemCount));

    return EtxEventWrite(&XBLA_149E11AEEvents[15], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_McItemAcquired, EventData);
}
#define EventEnabledMcItemUsed() (TRUE)

// Entry point to log the event McItemUsed
//
__inline
ULONG
EventWriteMcItemUsed(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ItemId, __in const float LocationX, __in const float LocationY, __in const float LocationZ, __in const signed int ItemAux, __in const unsigned __int64 ItemCount, __in const signed int Hunger)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_McItemUsed 14

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_McItemUsed];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], &ItemId, sizeof(ItemId));
    EventDataDescCreate(&EventData[8], &LocationX, sizeof(LocationX));
    EventDataDescCreate(&EventData[9], &LocationY, sizeof(LocationY));
    EventDataDescCreate(&EventData[10], &LocationZ, sizeof(LocationZ));
    EventDataDescCreate(&EventData[11], &ItemAux, sizeof(ItemAux));
    EventDataDescCreate(&EventData[12], &ItemCount, sizeof(ItemCount));
    EventDataDescCreate(&EventData[13], &Hunger, sizeof(Hunger));

    return EtxEventWrite(&XBLA_149E11AEEvents[16], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_McItemUsed, EventData);
}
#define EventEnabledMenuShown() (TRUE)

// Entry point to log the event MenuShown
//
__inline
ULONG
EventWriteMenuShown(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int MenuId, __in const signed int SubMenuId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_MenuShown 13

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_MenuShown];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &MenuId, sizeof(MenuId));
    EventDataDescCreate(&EventData[12], &SubMenuId, sizeof(SubMenuId));

    return EtxEventWrite(&XBLA_149E11AEEvents[17], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_MenuShown, EventData);
}
#define EventEnabledMobInteract() (TRUE)

// Entry point to log the event MobInteract
//
__inline
ULONG
EventWriteMobInteract(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int MobId, __in const signed int InteractionId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_MobInteract 5

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_MobInteract];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &MobId, sizeof(MobId));
    EventDataDescCreate(&EventData[4], &InteractionId, sizeof(InteractionId));

    return EtxEventWrite(&XBLA_149E11AEEvents[18], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_MobInteract, EventData);
}
#define EventEnabledMobKilled() (TRUE)

// Entry point to log the event MobKilled
//
__inline
ULONG
EventWriteMobKilled(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in LPCGUID RoundId, __in const signed int PlayerRoleId, __in const signed int PlayerWeaponId, __in const signed int EnemyRoleId, __in const signed int KillTypeId, __in const float LocationX, __in const float LocationY, __in const float LocationZ, __in const signed int EnemyWeaponId, __in const signed int Distance, __in const signed int MobId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_MobKilled 18

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_MobKilled];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[8], &PlayerRoleId, sizeof(PlayerRoleId));
    EventDataDescCreate(&EventData[9], &PlayerWeaponId, sizeof(PlayerWeaponId));
    EventDataDescCreate(&EventData[10], &EnemyRoleId, sizeof(EnemyRoleId));
    EventDataDescCreate(&EventData[11], &KillTypeId, sizeof(KillTypeId));
    EventDataDescCreate(&EventData[12], &LocationX, sizeof(LocationX));
    EventDataDescCreate(&EventData[13], &LocationY, sizeof(LocationY));
    EventDataDescCreate(&EventData[14], &LocationZ, sizeof(LocationZ));
    EventDataDescCreate(&EventData[15], &EnemyWeaponId, sizeof(EnemyWeaponId));
    EventDataDescCreate(&EventData[16], &Distance, sizeof(Distance));
    EventDataDescCreate(&EventData[17], &MobId, sizeof(MobId));

    return EtxEventWrite(&XBLA_149E11AEEvents[19], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_MobKilled, EventData);
}
#define EventEnabledMultiplayerRoundEnd() (TRUE)

// Entry point to log the event MultiplayerRoundEnd
//
__inline
ULONG
EventWriteMultiplayerRoundEnd(__in_opt PCWSTR UserId, __in LPCGUID RoundId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int MatchTypeId, __in const signed int DifficultyLevelId, __in const float TimeInSeconds, __in const signed int ExitStatusId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_MultiplayerRoundEnd 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_MultiplayerRoundEnd];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[4], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[5], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[6], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[7], &MatchTypeId, sizeof(MatchTypeId));
    EventDataDescCreate(&EventData[8], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[9], &TimeInSeconds, sizeof(TimeInSeconds));
    EventDataDescCreate(&EventData[10], &ExitStatusId, sizeof(ExitStatusId));

    return EtxEventWrite(&XBLA_149E11AEEvents[20], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_MultiplayerRoundEnd, EventData);
}
#define EventEnabledMultiplayerRoundStart() (TRUE)

// Entry point to log the event MultiplayerRoundStart
//
__inline
ULONG
EventWriteMultiplayerRoundStart(__in_opt PCWSTR UserId, __in LPCGUID RoundId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int MatchTypeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_MultiplayerRoundStart 9

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_MultiplayerRoundStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[4], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[5], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[6], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[7], &MatchTypeId, sizeof(MatchTypeId));
    EventDataDescCreate(&EventData[8], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&XBLA_149E11AEEvents[21], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_MultiplayerRoundStart, EventData);
}
#define EventEnabledOnARail() (TRUE)

// Entry point to log the event OnARail
//
__inline
ULONG
EventWriteOnARail(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int Distance)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_OnARail 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_OnARail];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &Distance, sizeof(Distance));

    return EtxEventWrite(&XBLA_149E11AEEvents[22], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_OnARail, EventData);
}
#define EventEnabledOverkill() (TRUE)

// Entry point to log the event Overkill
//
__inline
ULONG
EventWriteOverkill(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int Damage)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_Overkill 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_Overkill];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &Damage, sizeof(Damage));

    return EtxEventWrite(&XBLA_149E11AEEvents[23], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_Overkill, EventData);
}
#define EventEnabledPauseOrInactive() (TRUE)

// Entry point to log the event PauseOrInactive
//
__inline
ULONG
EventWritePauseOrInactive(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_PauseOrInactive 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_PauseOrInactive];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));

    return EtxEventWrite(&XBLA_149E11AEEvents[24], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_PauseOrInactive, EventData);
}
#define EventEnabledPlayedMusicDisc() (TRUE)

// Entry point to log the event PlayedMusicDisc
//
__inline
ULONG
EventWritePlayedMusicDisc(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int DiscId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_PlayedMusicDisc 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_PlayedMusicDisc];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &DiscId, sizeof(DiscId));

    return EtxEventWrite(&XBLA_149E11AEEvents[25], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_PlayedMusicDisc, EventData);
}
#define EventEnabledPlayerDiedOrFailed() (TRUE)

// Entry point to log the event PlayerDiedOrFailed
//
__inline
ULONG
EventWritePlayerDiedOrFailed(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int LowResMapX, __in const signed int LowResMapY, __in const signed int LowResMapZ, __in const signed int MapId, __in const signed int PlayerWeaponId, __in const signed int EnemyWeaponId, __in const signed int EnemyTypeId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_PlayerDiedOrFailed 18

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_PlayerDiedOrFailed];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &LowResMapX, sizeof(LowResMapX));
    EventDataDescCreate(&EventData[12], &LowResMapY, sizeof(LowResMapY));
    EventDataDescCreate(&EventData[13], &LowResMapZ, sizeof(LowResMapZ));
    EventDataDescCreate(&EventData[14], &MapId, sizeof(MapId));
    EventDataDescCreate(&EventData[15], &PlayerWeaponId, sizeof(PlayerWeaponId));
    EventDataDescCreate(&EventData[16], &EnemyWeaponId, sizeof(EnemyWeaponId));
    EventDataDescCreate(&EventData[17], &EnemyTypeId, sizeof(EnemyTypeId));

    return EtxEventWrite(&XBLA_149E11AEEvents[26], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_PlayerDiedOrFailed, EventData);
}
#define EventEnabledPlayerSessionEnd() (TRUE)

// Entry point to log the event PlayerSessionEnd
//
__inline
ULONG
EventWritePlayerSessionEnd(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ExitStatusId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionEnd 7

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionEnd];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[6], &ExitStatusId, sizeof(ExitStatusId));

    return EtxEventWrite(&XBLA_149E11AEEvents[27], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionEnd, EventData);
}
#define EventEnabledPlayerSessionPause() (TRUE)

// Entry point to log the event PlayerSessionPause
//
__inline
ULONG
EventWritePlayerSessionPause(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionPause 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionPause];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));

    return EtxEventWrite(&XBLA_149E11AEEvents[28], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionPause, EventData);
}
#define EventEnabledPlayerSessionResume() (TRUE)

// Entry point to log the event PlayerSessionResume
//
__inline
ULONG
EventWritePlayerSessionResume(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionResume 6

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionResume];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&XBLA_149E11AEEvents[29], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionResume, EventData);
}
#define EventEnabledPlayerSessionStart() (TRUE)

// Entry point to log the event PlayerSessionStart
//
__inline
ULONG
EventWritePlayerSessionStart(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionStart 6

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&XBLA_149E11AEEvents[30], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_PlayerSessionStart, EventData);
}
#define EventEnabledRecordMediaShareUpload() (TRUE)

// Entry point to log the event RecordMediaShareUpload
//
__inline
ULONG
EventWriteRecordMediaShareUpload(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_RecordMediaShareUpload 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_RecordMediaShareUpload];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));

    return EtxEventWrite(&XBLA_149E11AEEvents[31], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_RecordMediaShareUpload, EventData);
}
#define EventEnabledRichPresenceState() (TRUE)

// Entry point to log the event RichPresenceState
//
__inline
ULONG
EventWriteRichPresenceState(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int ContextID)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_RichPresenceState 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_RichPresenceState];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &ContextID, sizeof(ContextID));

    return EtxEventWrite(&XBLA_149E11AEEvents[32], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_RichPresenceState, EventData);
}
#define EventEnabledSkinChanged() (TRUE)

// Entry point to log the event SkinChanged
//
__inline
ULONG
EventWriteSkinChanged(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int SkinId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_SkinChanged 12

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_SkinChanged];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &SkinId, sizeof(SkinId));

    return EtxEventWrite(&XBLA_149E11AEEvents[33], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_SkinChanged, EventData);
}
#define EventEnabledTexturePackLoaded() (TRUE)

// Entry point to log the event TexturePackLoaded
//
__inline
ULONG
EventWriteTexturePackLoaded(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int TexturePackId, __in const BOOL Purchased)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_TexturePackLoaded 13

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_TexturePackLoaded];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &TexturePackId, sizeof(TexturePackId));
    EventDataDescCreate(&EventData[12], &Purchased, sizeof(Purchased));

    return EtxEventWrite(&XBLA_149E11AEEvents[34], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_TexturePackLoaded, EventData);
}
#define EventEnabledUnbanLevel() (TRUE)

// Entry point to log the event UnbanLevel
//
__inline
ULONG
EventWriteUnbanLevel(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_UnbanLevel 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_UnbanLevel];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));

    return EtxEventWrite(&XBLA_149E11AEEvents[35], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_UnbanLevel, EventData);
}
#define EventEnabledUnpauseOrActive() (TRUE)

// Entry point to log the event UnpauseOrActive
//
__inline
ULONG
EventWriteUnpauseOrActive(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_UnpauseOrActive 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_UnpauseOrActive];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));

    return EtxEventWrite(&XBLA_149E11AEEvents[36], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_UnpauseOrActive, EventData);
}
#define EventEnabledUpsellPresented() (TRUE)

// Entry point to log the event UpsellPresented
//
__inline
ULONG
EventWriteUpsellPresented(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int UpsellId, __in const signed int MarketplaceOfferId)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_UpsellPresented 13

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_UpsellPresented];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &UpsellId, sizeof(UpsellId));
    EventDataDescCreate(&EventData[12], &MarketplaceOfferId, sizeof(MarketplaceOfferId));

    return EtxEventWrite(&XBLA_149E11AEEvents[37], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_UpsellPresented, EventData);
}
#define EventEnabledUpsellResponded() (TRUE)

// Entry point to log the event UpsellResponded
//
__inline
ULONG
EventWriteUpsellResponded(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int SecondsSinceInitialize, __in const signed int Mode, __in const signed int SubMode, __in const signed int LevelId, __in const signed int SubLevelId, __in const signed int LeveInstanceId, __in LPCGUID PlayerSession, __in LPCGUID MultiplayerCorrelationId, __in const signed int UpsellId, __in const signed int MarketplaceOfferId, __in const signed int UpsellOutcome)
{
#define ARGUMENT_COUNT_XBLA_149E11AE_UpsellResponded 14

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_XBLA_149E11AE_UpsellResponded];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SecondsSinceInitialize, sizeof(SecondsSinceInitialize));
    EventDataDescCreate(&EventData[4], &Mode, sizeof(Mode));
    EventDataDescCreate(&EventData[5], &SubMode, sizeof(SubMode));
    EventDataDescCreate(&EventData[6], &LevelId, sizeof(LevelId));
    EventDataDescCreate(&EventData[7], &SubLevelId, sizeof(SubLevelId));
    EventDataDescCreate(&EventData[8], &LeveInstanceId, sizeof(LeveInstanceId));
    EventDataDescCreate(&EventData[9], PlayerSession, sizeof(GUID));
    EventDataDescCreate(&EventData[10], MultiplayerCorrelationId, sizeof(GUID));
    EventDataDescCreate(&EventData[11], &UpsellId, sizeof(UpsellId));
    EventDataDescCreate(&EventData[12], &MarketplaceOfferId, sizeof(MarketplaceOfferId));
    EventDataDescCreate(&EventData[13], &UpsellOutcome, sizeof(UpsellOutcome));

    return EtxEventWrite(&XBLA_149E11AEEvents[38], &XBLA_149E11AEProvider, XBLA_149E11AEHandle, ARGUMENT_COUNT_XBLA_149E11AE_UpsellResponded, EventData);
}
#if defined(__cplusplus)
};
#endif

#pragma pack(pop)
