#pragma once

enum eAward
{
	eAward_TakingInventory=0,	
	eAward_GettingWood,		
	eAward_Benchmarking,		
	eAward_TimeToMine,		
	eAward_HotTopic,			
	eAward_AquireHardware,	
	eAward_TimeToFarm,		
	eAward_BakeBread,			
	eAward_TheLie,			
	eAward_GettingAnUpgrade,	
	eAward_DeliciousFish,		
	eAward_OnARail,			
	eAward_TimeToStrike,		
	eAward_MonsterHunter,		
	eAward_CowTipper,			
	eAward_WhenPigsFly,		
	eAward_LeaderOfThePack,
	eAward_MOARTools,
	eAward_DispenseWithThis,
	eAward_InToTheNether,
	eAward_mine100Blocks,		
	eAward_kill10Creepers,	
	eAward_eatPorkChop,		
	eAward_play100Days,		
	eAward_arrowKillCreeper,	
	eAward_socialPost,		

	// 4J Stu - Does not map to any Xbox achievements
	eAward_snipeSkeleton,	
	eAward_diamonds,
	eAward_portal,
	eAward_ghast,
	eAward_blazeRod,
	eAward_potion,
	eAward_theEnd,
	eAward_winGame,
	eAward_enchantments,
	eAward_overkill,
	eAward_bookcase,

	eAward_Max,
};