#pragma once

#ifdef _WINDOWS64

#include <Windows.h>
#include "KeyboardInput.h"

// TODO: Make reassignable in game, for now is hardcoded
#define KB_MENU_OK VK_RETURN
#define KB_MENU_CANCEL VK_ESCAPE
#define KB_MENU_UP VK_UP
#define KB_MENU_DOWN VK_DOWN
#define KB_MENU_LEFT VK_LEFT
#define KB_MENU_RIGHT VK_RIGHT
#define KB_MENU_PAGEUP VK_PRIOR
#define KB_MENU_PAGEDOWN VK_NEXT
#define KB_MENU_PAUSEMENU VK_ESCAPE
#define KB_MENU_Y VK_E
#define KB_MENU_X VK_R
#define KB_MENU_RIGHT_SCROLL VK_X
#define KB_MENU_LEFT_SCROLL VK_Z

#define KB_ACTION_FORWARD VK_W
#define KB_ACTION_BACKWARD VK_S
#define KB_ACTION_LEFT VK_A
#define KB_ACTION_RIGHT VK_D
#define KB_ACTION_JUMP VK_SPACE
#define KB_ACTION_DPAD_LEFT VK_LEFT
#define KB_ACTION_DPAD_RIGHT VK_RIGHT
#define KB_ACTION_DPAD_UP VK_UP
#define KB_ACTION_DPAD_DOWN VK_DOWN
#define KB_ACTION_LEFT_SCROLL VK_X
#define KB_ACTION_RIGHT_SCROLL VK_Z
#define KB_ACTION_INVENTORY VK_E
#define KB_ACTION_PAUSEMENU VK_ESCAPE
#define KB_ACTION_DROP VK_Q
#define KB_ACTION_CRAFTING VK_R
#define KB_ACTION_RENDER_THIRD_PERSON VK_F5
#define KB_ACTION_GAME_INFO VK_F3
#define KB_ACTION_SNEAK VK_SHIFT
#define KB_ACTION_SPRINT VK_CONTROL

#endif